#!/usr/bin/env node

// This will combine other functions for a complete solution


// check EPF for new full file

// merge each EPF into duckdb

// using errors in application_detail/application find missing records, fill them in with bulk API

// export new data to parquet & upload to s3


