#!/bin/bash

# Very simple import script that leverages bunzip2 unix-command and duckdb CLI to import, streaming

set -e

for file in $(find data/epf -name '*.tbz'); do
  table=$(basename "${file}" .tbz)
  echo "Importing ${table}"
  bunzip2 "${file}" | node ./lib/epf2csv.js | duckdb data/epf.duckdb -c "CREATE TABLE ${table} AS SELECT * FROM read_csv('/dev/stdin', header=true)"
done
